[package]
name = "chef"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.57", features = ["derive"] }
md-5 = "0.10.6"
nom = "8.0.0"
percent-encoding-rfc3986 = "0.1.3"
sha1 = "0.10.6"
sha2 = "0.10.8"
